### ISSUE TITLE
Código

### ISSUE THREAD

**Issue by gleandroj** [moothz/henry7py#1]
Olá, estou pesquisando sobre integração com essa catraca,
tentei rodar seu código mas aparentemente não está mapeado corretamento o protocolo.
Você tem mais informações sobre como funciona esse protocolo ?

Desde já,
Grato!

**Comment by moothz** [comment]
Opa, e aí!

A princípio o código segue funcionando até hoje nas nossas catracas
(incrivelmente). Eu tenho aqui um documento que recebi do pessoal da Henry
na época (2014), acabei esquecendo de anexá-lo no projeto, mas já dei um commit com ele.

Att.
Jeann

**Comment by gleandroj** [comment]
Obrigado Jeann!
