### ISSUE TITLE
Emulador

### ISSUE THREAD

**Issue by mjacr** [moothz/henry7py#2]
existe alguma forma de testar essa comunicação sem ter a catraca?
existe algum emulador para executar testes de integração com a catraca?

**Comment by moothz** [comment]
Opa!

Então, eu não trabalho na empresa, só fiz esse wrapper com base na
documentação que me passaram (eles só tinha biblioteca em delphi na época).
Talvez a empresa tenha um software de simulação, mas acho difícil.

Tu poderia reaproveitar um pedaço do código de comunicação e fazer um
servidor que escuta os comandos e responde conforme a documentação, mas vai
dar um certo trabalhar implementar tudo.

Em ter., 14 de set. de 2021 às 20:26, Marcos Rocha ***@***.***>
escreveu:
